import type { Capacitacion, ColaboradorCapacitacion } from "./capacitaciones-types"

// Mock Capacitaciones Data
export const mockCapacitaciones: Capacitacion[] = [
  {
    ID_CAPACITACION: 1,
    CODIGO_DOCUMENTO: "CAP-2025-001",
    NOMBRE: "Seguridad e Higiene en el Laboratorio",
    OBJETIVO: "Capacitar al personal en las normas de seguridad y buenas prácticas de laboratorio",
    VERSION: 1,
    ES_SISTEMA_DOCUMENTAL: true,
    TIPO_CAPACITACION: "CURSO",
    MODALIDAD: "INTERNA",
    GRUPO_OBJETIVO: "Personal de laboratorio nuevo",
    CAPACITADOR_ID: 2,
    CAPACITADOR_NOMBRE: "Carlos López",
    FECHA_PROGRAMADA: "2025-02-15",
    FECHA_INICIO: "2025-02-15",
    HORA_INICIO: "09:00:00",
    HORA_FIN: "12:00:00",
    DURACION_MINUTOS: 180,
    HORARIO_FORMATO: "09:00 AM a 12:00 PM",
    DURACION_FORMATO: "3h",
    APLICA_EXAMEN: true,
    NOTA_MINIMA: 70,
    APLICA_DIPLOMA: true,
    ESTADO: "EN_PROCESO",
    URL_LISTA_ASISTENCIA: null,
    OBSERVACIONES: "",
    TIPO_ORIGEN: "PLAN",
    NOMBRE_ORIGEN: "Plan Anual de Capacitación 2025",
    TEMAS: "Normas de seguridad, Equipo de protección personal, Manejo de residuos, Primeros auxilios",
    TOTAL_COLABORADORES_PENDIENTES: 15,
  },
  {
    ID_CAPACITACION: 2,
    CODIGO_DOCUMENTO: "CAP-2025-002",
    NOMBRE: "Manejo de Equipos de Análisis",
    OBJETIVO: "Entrenar al personal en el uso correcto de equipos de análisis químico",
    VERSION: 1,
    ES_SISTEMA_DOCUMENTAL: true,
    TIPO_CAPACITACION: "TALLER",
    MODALIDAD: "INTERNA",
    GRUPO_OBJETIVO: "Técnicos de laboratorio",
    CAPACITADOR_ID: 2,
    CAPACITADOR_NOMBRE: "Carlos López",
    FECHA_PROGRAMADA: "2025-02-20",
    FECHA_INICIO: null,
    HORA_INICIO: "14:00:00",
    HORA_FIN: "17:00:00",
    DURACION_MINUTOS: 180,
    HORARIO_FORMATO: "02:00 PM a 05:00 PM",
    DURACION_FORMATO: "3h",
    APLICA_EXAMEN: true,
    NOTA_MINIMA: 75,
    APLICA_DIPLOMA: false,
    ESTADO: "ASIGNADA",
    URL_LISTA_ASISTENCIA: null,
    OBSERVACIONES: "",
    TIPO_ORIGEN: "PLAN",
    NOMBRE_ORIGEN: "Plan Anual de Capacitación 2025",
    TEMAS: "Espectrofotómetro, Cromatógrafo, Balanzas analíticas, Calibración de equipos",
    TOTAL_COLABORADORES_PENDIENTES: 12,
  },
  {
    ID_CAPACITACION: 3,
    CODIGO_DOCUMENTO: null,
    NOMBRE: "Atención al Cliente y Comunicación Efectiva",
    OBJETIVO: "Mejorar las habilidades de comunicación del personal de atención al cliente",
    VERSION: null,
    ES_SISTEMA_DOCUMENTAL: false,
    TIPO_CAPACITACION: "CHARLA",
    MODALIDAD: "EXTERNA",
    GRUPO_OBJETIVO: "Personal de recepción y atención al cliente",
    CAPACITADOR_ID: null,
    CAPACITADOR_NOMBRE: "Por asignar",
    FECHA_PROGRAMADA: "2025-03-01",
    FECHA_INICIO: null,
    HORA_INICIO: "10:00:00",
    HORA_FIN: "12:00:00",
    DURACION_MINUTOS: 120,
    HORARIO_FORMATO: "10:00 AM a 12:00 PM",
    DURACION_FORMATO: "2h",
    APLICA_EXAMEN: false,
    NOTA_MINIMA: null,
    APLICA_DIPLOMA: false,
    ESTADO: "PENDIENTE_ASIGNACION",
    URL_LISTA_ASISTENCIA: null,
    OBSERVACIONES: "",
    TIPO_ORIGEN: "PROGRAMA",
    NOMBRE_ORIGEN: "Programa de Desarrollo de Habilidades Blandas",
    TEMAS: "Comunicación asertiva, Manejo de quejas, Empatía, Resolución de conflictos",
    TOTAL_COLABORADORES_PENDIENTES: 8,
  },
  {
    ID_CAPACITACION: 4,
    CODIGO_DOCUMENTO: "CAP-2025-003",
    NOMBRE: "Control de Calidad en Procesos de Laboratorio",
    OBJETIVO: "Implementar procedimientos de control de calidad en todas las áreas del laboratorio",
    VERSION: 2,
    ES_SISTEMA_DOCUMENTAL: true,
    TIPO_CAPACITACION: "CURSO",
    MODALIDAD: "INTERNA",
    GRUPO_OBJETIVO: "Todo el personal técnico",
    CAPACITADOR_ID: 2,
    CAPACITADOR_NOMBRE: "Carlos López",
    FECHA_PROGRAMADA: "2025-01-30",
    FECHA_INICIO: "2025-01-30",
    HORA_INICIO: "08:00:00",
    HORA_FIN: "12:00:00",
    DURACION_MINUTOS: 240,
    HORARIO_FORMATO: "08:00 AM a 12:00 PM",
    DURACION_FORMATO: "4h",
    APLICA_EXAMEN: true,
    NOTA_MINIMA: 80,
    APLICA_DIPLOMA: true,
    ESTADO: "FINALIZADA_CAPACITADOR",
    URL_LISTA_ASISTENCIA: "/documents/lista-asistencia-cap-4.pdf",
    OBSERVACIONES: "Capacitación completada exitosamente. Todos los participantes aprobaron.",
    TIPO_ORIGEN: "PLAN",
    NOMBRE_ORIGEN: "Plan Anual de Capacitación 2025",
    TEMAS: "ISO 17025, Validación de métodos, Cartas de control, Auditorías internas",
    TOTAL_COLABORADORES_PENDIENTES: 20,
  },
  {
    ID_CAPACITACION: 5,
    CODIGO_DOCUMENTO: "CAP-2024-045",
    NOMBRE: "Prevención de Riesgos Laborales",
    OBJETIVO: "Concientizar sobre los riesgos laborales y medidas preventivas",
    VERSION: 1,
    ES_SISTEMA_DOCUMENTAL: true,
    TIPO_CAPACITACION: "CHARLA",
    MODALIDAD: "INTERNA",
    GRUPO_OBJETIVO: "Todo el personal",
    CAPACITADOR_ID: 2,
    CAPACITADOR_NOMBRE: "Carlos López",
    FECHA_PROGRAMADA: "2024-12-15",
    FECHA_INICIO: "2024-12-15",
    HORA_INICIO: "15:00:00",
    HORA_FIN: "16:30:00",
    DURACION_MINUTOS: 90,
    HORARIO_FORMATO: "03:00 PM a 04:30 PM",
    DURACION_FORMATO: "1h 30min",
    APLICA_EXAMEN: false,
    NOTA_MINIMA: null,
    APLICA_DIPLOMA: false,
    ESTADO: "FINALIZADA",
    URL_LISTA_ASISTENCIA: "/documents/lista-asistencia-cap-5.pdf",
    OBSERVACIONES: "Capacitación finalizada y aprobada por RRHH",
    TIPO_ORIGEN: "PLAN",
    NOMBRE_ORIGEN: "Plan Anual de Capacitación 2024",
    TEMAS: "Identificación de riesgos, EPP, Ergonomía, Señalización de seguridad",
    TOTAL_COLABORADORES_PENDIENTES: 35,
  },
]

// Mock Colaboradores en Capacitaciones
export const mockColaboradoresCapacitacion: ColaboradorCapacitacion[] = [
  // Capacitación 1 - EN_PROCESO
  {
    ID_CAPACITACION: 1,
    ID_COLABORADOR: 101,
    NOMBRE_COMPLETO: "Juan Pérez García",
    CORREO: "juan.perez@phara.com",
    DEPARTAMENTO: "Laboratorio Clínico",
    PUESTO: "Técnico de Laboratorio",
    ASISTIO: true,
    FECHA_ASISTENCIA: "2025-02-15",
    NOTA_OBTENIDA: null,
    APROBADO: null,
    URL_EXAMEN: null,
    URL_DIPLOMA: null,
    OBSERVACIONES: "",
    ESTADO_COLABORADOR: "ASISTIO_SIN_EVALUAR",
  },
  {
    ID_CAPACITACION: 1,
    ID_COLABORADOR: 102,
    NOMBRE_COMPLETO: "María Rodríguez López",
    CORREO: "maria.rodriguez@phara.com",
    DEPARTAMENTO: "Laboratorio Clínico",
    PUESTO: "Técnico de Laboratorio",
    ASISTIO: true,
    FECHA_ASISTENCIA: "2025-02-15",
    NOTA_OBTENIDA: 85,
    APROBADO: true,
    URL_EXAMEN: "/documents/examen-cap1-col102.pdf",
    URL_DIPLOMA: "/documents/diploma-cap1-col102.pdf",
    OBSERVACIONES: "Excelente desempeño",
    ESTADO_COLABORADOR: "APROBADO",
  },
  {
    ID_CAPACITACION: 1,
    ID_COLABORADOR: 103,
    NOMBRE_COMPLETO: "Pedro Martínez Sánchez",
    CORREO: "pedro.martinez@phara.com",
    DEPARTAMENTO: "Laboratorio Clínico",
    PUESTO: "Auxiliar de Laboratorio",
    ASISTIO: false,
    FECHA_ASISTENCIA: null,
    NOTA_OBTENIDA: null,
    APROBADO: null,
    URL_EXAMEN: null,
    URL_DIPLOMA: null,
    OBSERVACIONES: "Ausente por enfermedad",
    ESTADO_COLABORADOR: "NO_ASISTIO",
  },
  {
    ID_CAPACITACION: 1,
    ID_COLABORADOR: 104,
    NOMBRE_COMPLETO: "Ana Gómez Torres",
    CORREO: "ana.gomez@phara.com",
    DEPARTAMENTO: "Laboratorio Clínico",
    PUESTO: "Técnico de Laboratorio",
    ASISTIO: null,
    FECHA_ASISTENCIA: null,
    NOTA_OBTENIDA: null,
    APROBADO: null,
    URL_EXAMEN: null,
    URL_DIPLOMA: null,
    OBSERVACIONES: "",
    ESTADO_COLABORADOR: "PENDIENTE",
  },
  // Capacitación 2 - ASIGNADA
  {
    ID_CAPACITACION: 2,
    ID_COLABORADOR: 105,
    NOMBRE_COMPLETO: "Luis Hernández Díaz",
    CORREO: "luis.hernandez@phara.com",
    DEPARTAMENTO: "Laboratorio Químico",
    PUESTO: "Técnico Químico",
    ASISTIO: null,
    FECHA_ASISTENCIA: null,
    NOTA_OBTENIDA: null,
    APROBADO: null,
    URL_EXAMEN: null,
    URL_DIPLOMA: null,
    OBSERVACIONES: "",
    ESTADO_COLABORADOR: "PENDIENTE",
  },
  {
    ID_CAPACITACION: 2,
    ID_COLABORADOR: 106,
    NOMBRE_COMPLETO: "Carmen Flores Ruiz",
    CORREO: "carmen.flores@phara.com",
    DEPARTAMENTO: "Laboratorio Químico",
    PUESTO: "Técnico Químico",
    ASISTIO: null,
    FECHA_ASISTENCIA: null,
    NOTA_OBTENIDA: null,
    APROBADO: null,
    URL_EXAMEN: null,
    URL_DIPLOMA: null,
    OBSERVACIONES: "",
    ESTADO_COLABORADOR: "PENDIENTE",
  },
  // Capacitación 4 - FINALIZADA_CAPACITADOR
  {
    ID_CAPACITACION: 4,
    ID_COLABORADOR: 107,
    NOMBRE_COMPLETO: "Roberto Silva Castro",
    CORREO: "roberto.silva@phara.com",
    DEPARTAMENTO: "Control de Calidad",
    PUESTO: "Analista de Calidad",
    ASISTIO: true,
    FECHA_ASISTENCIA: "2025-01-30",
    NOTA_OBTENIDA: 92,
    APROBADO: true,
    URL_EXAMEN: "/documents/examen-cap4-col107.pdf",
    URL_DIPLOMA: "/documents/diploma-cap4-col107.pdf",
    OBSERVACIONES: "Participación activa",
    ESTADO_COLABORADOR: "APROBADO",
  },
  {
    ID_CAPACITACION: 4,
    ID_COLABORADOR: 108,
    NOMBRE_COMPLETO: "Laura Morales Vega",
    CORREO: "laura.morales@phara.com",
    DEPARTAMENTO: "Control de Calidad",
    PUESTO: "Analista de Calidad",
    ASISTIO: true,
    FECHA_ASISTENCIA: "2025-01-30",
    NOTA_OBTENIDA: 88,
    APROBADO: true,
    URL_EXAMEN: "/documents/examen-cap4-col108.pdf",
    URL_DIPLOMA: "/documents/diploma-cap4-col108.pdf",
    OBSERVACIONES: "",
    ESTADO_COLABORADOR: "APROBADO",
  },
]

// Helper function to get colaboradores by capacitacion ID
export function getColaboradoresByCapacitacion(idCapacitacion: number): ColaboradorCapacitacion[] {
  return mockColaboradoresCapacitacion.filter((col) => col.ID_CAPACITACION === idCapacitacion)
}

// Helper function to get capacitaciones by capacitador ID
export function getCapacitacionesByCapacitador(capacitadorId: number): Capacitacion[] {
  return mockCapacitaciones.filter((cap) => cap.CAPACITADOR_ID === capacitadorId)
}

// Helper function to get capacitaciones by estado
export function getCapacitacionesByEstado(estado: string): Capacitacion[] {
  return mockCapacitaciones.filter((cap) => cap.ESTADO === estado)
}
